[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings=["@chainlink/=lib/foundry-chainlink-toolkit/src"]

[rpc_endpoints]
buildbear="https://rpc.buildbear.io/sensitive-katebishop-8c1e5d33"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
